apiVersion: v1
kind: Secret
metadata:
  name: {{ include "current.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "current.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ randAlphaNum 32 | quote }}
  JWT_SECRET_KEY: {{ randAlphaNum 32 | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | default "app_user" | quote }}
  DB_PASS: {{ .Values.postgresql.auth.password | default "changeme" | quote }}
  DEFAULT_ADMIN_EMAIL: "admin@localhost.local"
  DEFAULT_ADMIN_PASSWORD: "admin123"
